### ISSUE TITLE
No accessory to be added in Home app

### ISSUE THREAD

**Issue by edugrt** [RaresAil/homebridge-daikin-smart-ac#1]
Hello! Could you, please, guide me on how it
is supposed to add the AC accessory to the Home app? I setup your plugin in Homebridge with the correct AC IP but no additional accessory shows up in Home app, even when I try to add a new accessory using the Homebridge 8 digit code. Thanks!

**Comment by RaresAil** [comment]
Hello, can you provide the logs from homebridge?

**Comment by edugrt** [comment]
[10/13/2022, 9:04:54 AM] Loaded plugin: homebridge-daikin-smart-ac@1.0.0
[10/13/2022, 9:04:54 AM] Registering platform 'homebridge-daikin-smart-ac.DaikinSmartAC'
[10/13/2022, 9:04:54 AM] ---
[10/13/2022, 9:05:12 AM] [Suíte Master] Initializing DaikinSmartAC platform...
[10/13/2022, 9:05:12 AM] Loading 41 accessories...
[10/13/2022, 9:05:20 AM] [Suíte Master] Failed to setup Daikin AC (192.168.100.102)

**Comment by edugrt** [comment]
I missed an important part of the log:

[10/13/2022, 9:04:54 AM] Loaded plugin: homebridge-daikin-smart-ac@1.0.0
[10/13/2022, 9:04:54 AM] Registering platform 'homebridge-daikin-smart-ac.DaikinSmartAC'
[10/13/2022, 9:04:54 AM] ---
[10/13/2022, 9:05:12 AM] [Suíte Master] Initializing DaikinSmartAC platform...
[10/13/2022, 9:05:12 AM] Loading 41 accessories...
[10/13/2022, 9:05:20 AM] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 2628) is running on port 51740.
[10/13/2022, 9:05:20 AM] [Suíte Master] AxiosError: connect ECONNREFUSED 192.168.100.102:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  port: 80,
  address: '192.168.100.102',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.27.2'
    },
    method: 'get',
    url: 'http://192.168.100.102/common/basic_info',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/common/basic_info',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.100.102',
      port: null,
      nativeProtocols: [Object],
      pathname: '/common/basic_info'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /common/basic_info HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Host: 192.168.100.102\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/common/basic_info',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.100.102',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.100.102/common/basic_info',
    [Symbol(kCapture)]: false
  }
}
[10/13/2022, 9:05:20 AM] [Suíte Master] Failed to setup Daikin AC (192.168.100.102)

**Comment by RaresAil** [comment]
Does the AC appear on router connected devices and can you provide a image with the wifi adapter?

**Comment by edugrt** [comment]
Yes, the AC is connected to the router and working properly using the original iOS app. There is no external wifi adapter. This AC model comes with an embedded wifi board attached to its internal parts. Its an ESP board. I have a picture of the board.

**Comment by edugrt** [comment]
![9F6B8AF7-485E-40BD-91FE-7D357DEA0500](https://user-images.githubusercontent.com/73726734/195612410-de860dce-5b4f-43de-b12f-685eb479dfc9.jpeg)

**Comment by RaresAil** [comment]
@edugrt Does the iOS app require any password for it to work?

**Comment by edugrt** [comment]
Oh, yes, it does

**Comment by RaresAil** [comment]
I think that is the issue, the plugin is made to work the the local versions and with remote control disabled, if you can disable the remote control (for security) and get rid of the password, the plugin it will work
