### ISSUE TITLE
Adjust temperature using automation

### ISSUE THREAD

**Issue by kfakhri1** [RaresAil/homebridge-daikin-smart-ac#2]
**Describe The Bug:**
Using location based automation im unable to reduce the heating temperature.  I have my units set at 68f, the automation request is to set it to 60f when the last person leaves the house.  Once the automation runs, the heat temperature stays at 68f.  I’m able to run the automation if I set it to completely turn off the unit.

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by RaresAil** [comment]
Can you provide the logs?

**Comment by kfakhri1** [comment]
Yes, I’ll add the logs on Wednesday. I’ll  have access to them then.  Thank you.

**Comment by RaresAil** [comment]
No response
